nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: ""
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    path: /healthz
    initialDelaySeconds: 2
    periodSeconds: 5

ingress:
  enabled: false
  className: alb
  annotations: {}
  hosts: []
  tls: []

env: []

nodeSelector: {}
tolerations: []
affinity: {}
