replicaCount: 1

image:
  repository: 527055790396.dkr.ecr.ap-southeast-1.amazonaws.com/shopxpress-gateway
  tag: sha-0a500bd
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080

env:
  - name: SERVICE
    value: gateway
  - name: PORT
    value: "8080"

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/group.name: shopxpress-public
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:527055790396:certificate/c3dab8e5-1190-4b24-9a95-46480ac6b0b9
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    external-dns.alpha.kubernetes.io/hostname: api-dev.shopxpress.do2602.click
  hosts:
    - host: api-dev.shopxpress.do2602.click
      paths:
        - path: /
          pathType: Prefix
