replicaCount: 1

image:
  repository: 527055790396.dkr.ecr.ap-southeast-1.amazonaws.com/shopxpress-products
  tag: sha-0a500bd
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8081

env:
  - name: SERVICE
    value: products
  - name: PORT
    value: "8081"
